require('dotenv').config({ path: require('path').resolve(__dirname, '../../.env') });
const mongoose = require('mongoose');
const slugify = require('slugify');
const School = require('../models/School');
const Scholarship = require('../models/Scholarship');
const { Admin } = require('../models/index');

const slug = (name) => slugify(name, { lower: true, strict: true });

const seed = async () => {
  await mongoose.connect(process.env.MONGODB_URI);
  console.log('Connected to MongoDB');

  // Clear existing
  await Promise.all([School.deleteMany(), Scholarship.deleteMany()]);

  // Drop slug indexes to avoid null-key conflicts (insertMany bypasses pre-save hooks)
  try { await School.collection.dropIndex('slug_1'); } catch (e) {}
  try { await Scholarship.collection.dropIndex('slug_1'); } catch (e) {}

  // Create admin
  const existingAdmin = await Admin.findOne({ email: process.env.ADMIN_EMAIL });
  if (!existingAdmin) {
    await Admin.create({
      firstName: 'Platform',
      lastName: 'Admin',
      email: process.env.ADMIN_EMAIL || 'schoolgates0@gmail.com',
      password: process.env.ADMIN_PASSWORD || 'Musamarch@121',
      role: 'platform_admin',
    });
    console.log('Admin created');
  }

  const schools = await School.insertMany([
    {
      name: 'Phillips Exeter Academy',
      slug: slug('Phillips Exeter Academy'),
      type: 'boarding',
      category: 'private',
      location: { city: 'Exeter', state: 'New Hampshire', country: 'USA' },
      founded: 1781,
      overview: 'One of the most prestigious boarding schools in the United States, Phillips Exeter Academy is known for its rigorous academics and the Harkness method of education. With a history spanning over 240 years, Exeter has produced Nobel laureates, heads of state, and Fortune 500 CEOs.',
      mission: 'Non sibi — Not for oneself. Phillips Exeter Academy is committed to educating youth from every quarter.',
      tuition: { annual: 60000, boarding: 18000, fees: 4500, currency: 'USD' },
      stats: {
        totalStudents: 1080,
        internationalStudents: 230,
        studentTeacherRatio: '5:1',
        avgClassSize: 12,
        graduationRate: 100,
        collegeAcceptanceRate: 99,
        satAverage: 1480,
        apCourses: 42,
      },
      programs: ['STEM', 'Humanities', 'Arts', 'Athletic Excellence', 'Leadership', 'Computer Science', 'International Studies'],
      sports: ['Rowing', 'Lacrosse', 'Swimming', 'Tennis', 'Basketball', 'Ice Hockey', 'Soccer'],
      arts: ['Theater', 'Orchestra', 'Jazz Ensemble', 'Visual Arts', 'Creative Writing'],
      facilities: ['Squash Courts', 'Ice Rink', 'Olympic Pool', 'Theater', 'Art Studios', '900-seat Library', 'Science Labs', 'Fitness Center'],
      contactInfo: {
        email: 'admissions@exeter.edu',
        phone: '+1 (603) 772-4311',
        website: 'https://www.exeter.edu',
        admissionsEmail: 'admit@exeter.edu',
      },
      accreditation: ['NEASC'],
      affiliations: ['G20 Schools', 'Eight Schools Association'],
      featured: true,
    },
    {
      name: 'Phillips Academy Andover',
      slug: slug('Phillips Academy Andover'),
      type: 'boarding',
      category: 'private',
      location: { city: 'Andover', state: 'Massachusetts', country: 'USA' },
      founded: 1778,
      overview: 'Phillips Academy Andover is a leading independent boarding school offering a transformative education to talented students from around the world. Founded in 1778, Andover is one of the oldest secondary schools in the United States and consistently ranked among the top boarding schools globally.',
      mission: 'Youth from every quarter. Andover believes in the promise of every student and offers an exceptional education to those who demonstrate intellectual potential and personal character.',
      tuition: { annual: 62000, boarding: 19000, fees: 5000, currency: 'USD' },
      stats: {
        totalStudents: 1150,
        internationalStudents: 280,
        studentTeacherRatio: '4:1',
        avgClassSize: 13,
        graduationRate: 100,
        collegeAcceptanceRate: 99,
        satAverage: 1490,
        apCourses: 46,
      },
      programs: ['STEM', 'Visual Arts', 'Performing Arts', 'Athletics', 'Community Service', 'Global Leaders', 'Innovation Lab'],
      sports: ['Football', 'Crew', 'Field Hockey', 'Golf', 'Wrestling', 'Swimming', 'Cross Country'],
      arts: ['Dance', 'Film', 'Photography', 'Ceramics', 'Sculpture', 'A Cappella'],
      facilities: ['Peabody Museum', 'Addison Gallery of American Art', 'Athletic Complex', 'Oliver Wendell Holmes Library', 'STEM Innovation Center', 'Recording Studio'],
      contactInfo: {
        email: 'admissions@andover.edu',
        phone: '+1 (978) 749-4050',
        website: 'https://www.andover.edu',
        admissionsEmail: 'admissions@andover.edu',
      },
      accreditation: ['NEASC'],
      affiliations: ['Eight Schools Association', 'G20 Schools'],
      featured: true,
    },
    {
      name: 'The Lawrenceville School',
      slug: slug('The Lawrenceville School'),
      type: 'boarding',
      category: 'private',
      location: { city: 'Lawrenceville', state: 'New Jersey', country: 'USA' },
      founded: 1810,
      overview: 'The Lawrenceville School is a world-class boarding school known for its distinctive house system, passionate community, and academic excellence. Located just 3 miles from Princeton University, students benefit from extraordinary academic and cultural resources.',
      mission: 'Lawrenceville aspires to inspire and cultivate in each student the unique spark of greatness.',
      tuition: { annual: 58000, boarding: 17000, fees: 4000, currency: 'USD' },
      stats: {
        totalStudents: 830,
        internationalStudents: 190,
        studentTeacherRatio: '6:1',
        avgClassSize: 12,
        graduationRate: 100,
        collegeAcceptanceRate: 98,
        satAverage: 1460,
        apCourses: 38,
      },
      programs: ['Math & Science', 'Humanities', 'Arts', 'Global Studies', 'Entrepreneurship', 'Environmental Studies'],
      sports: ['Squash', 'Tennis', 'Fencing', 'Rugby', 'Volleyball', 'Track & Field', 'Skiing'],
      arts: ['Theater', 'Orchestra', 'Choir', 'Dance Company', 'Literary Magazine'],
      facilities: ['House System Dormitories', 'Chapel', 'Athletic Fields', 'Innovation Lab', 'Greenhouse', 'Aquatic Center'],
      contactInfo: {
        email: 'admission@lawrenceville.org',
        phone: '+1 (609) 896-0400',
        website: 'https://www.lawrenceville.org',
        admissionsEmail: 'admission@lawrenceville.org',
      },
      accreditation: ['MSA', 'NEASC'],
      affiliations: ['Eight Schools Association'],
      featured: true,
    },
    {
      name: 'The Hotchkiss School',
      slug: slug('The Hotchkiss School'),
      type: 'boarding',
      category: 'private',
      location: { city: 'Lakeville', state: 'Connecticut', country: 'USA' },
      founded: 1891,
      overview: 'Nestled in the rolling hills of northwest Connecticut, The Hotchkiss School offers a transformative education on a breathtaking 545-acre campus. Hotchkiss is celebrated for its commitment to academic excellence, character development, and preparing students for leadership roles in a global society.',
      mission: 'Hotchkiss exists to prepare young people for full, meaningful lives — as passionate learners, as people of good character, and as citizens of a complex world.',
      tuition: { annual: 63000, boarding: 20000, fees: 5500, currency: 'USD' },
      stats: {
        totalStudents: 600,
        internationalStudents: 150,
        studentTeacherRatio: '5:1',
        avgClassSize: 11,
        graduationRate: 100,
        collegeAcceptanceRate: 99,
        satAverage: 1470,
        apCourses: 30,
      },
      programs: ['STEM', 'Social Sciences', 'Fine Arts', 'Music Conservatory', 'Global Citizenship', 'Environmental Studies'],
      sports: ['Skiing', 'Squash', 'Lacrosse', 'Crew', 'Cross Country', 'Soccer', 'Baseball'],
      arts: ['Art Museum', 'Theater', 'Dance', 'Music', 'Photography'],
      facilities: ['Ludd-Leavenworth Art Museum', 'Lavino Hockey Rink', 'Whitehead Campus Center', 'Ford Science Center', 'Aquatic Center', '9-Hole Golf Course'],
      contactInfo: {
        email: 'admission@hotchkiss.org',
        phone: '+1 (860) 435-3102',
        website: 'https://www.hotchkiss.org',
        admissionsEmail: 'admission@hotchkiss.org',
      },
      accreditation: ['NEASC'],
      affiliations: ['Eight Schools Association'],
      featured: true,
    },
    {
      name: 'Deerfield Academy',
      slug: slug('Deerfield Academy'),
      type: 'boarding',
      category: 'private',
      location: { city: 'Deerfield', state: 'Massachusetts', country: 'USA' },
      founded: 1797,
      overview: "Deerfield Academy stands as one of America's most historic and distinguished boarding schools. Set in the picturesque Pioneer Valley of Massachusetts, Deerfield combines rigorous academics with an exceptional community culture that instills lifelong values of integrity and service.",
      mission: "Deerfield's mission is to provide a superior education that enables each student to realize their full potential — intellectually, physically, and morally.",
      tuition: { annual: 61000, boarding: 18500, fees: 4200, currency: 'USD' },
      stats: {
        totalStudents: 650,
        internationalStudents: 160,
        studentTeacherRatio: '5:1',
        avgClassSize: 12,
        graduationRate: 100,
        collegeAcceptanceRate: 99,
        satAverage: 1465,
        apCourses: 35,
      },
      programs: ['STEM Innovation', 'Humanities', 'Arts Conservatory', 'Athletics & Wellness', 'Entrepreneurship', 'Environmental Science'],
      sports: ['Football', 'Basketball', 'Swimming', 'Golf', 'Tennis', 'Ice Hockey', 'Lacrosse'],
      arts: ['Hess Center for Arts', 'Theater', 'Orchestra', 'Ceramics Studio', 'Photography Darkroom'],
      facilities: ['Hess Center for Arts', 'Koch Athletic Center', 'Science & Math Center', 'Historic Deerfield Village Access', 'Olympic-Size Pool', 'State-of-the-Art Library'],
      contactInfo: {
        email: 'admission@deerfield.edu',
        phone: '+1 (413) 774-1400',
        website: 'https://www.deerfield.edu',
        admissionsEmail: 'admission@deerfield.edu',
      },
      accreditation: ['NEASC'],
      affiliations: ['Eight Schools Association'],
      featured: true,
    },
    {
      name: 'Milton Academy',
      slug: slug('Milton Academy'),
      type: 'boarding-day',
      category: 'private',
      location: { city: 'Milton', state: 'Massachusetts', country: 'USA' },
      founded: 1798,
      overview: 'Milton Academy sits on a beautiful 125-acre campus just 8 miles from Boston, offering students extraordinary access to one of the world\'s great cultural and academic cities. Milton is known for its intellectually curious community and commitment to developing the whole student.',
      mission: 'Dare to be true. Milton Academy challenges students to live with integrity and to make a difference in the world.',
      tuition: { annual: 59000, boarding: 17500, fees: 3800, currency: 'USD' },
      stats: {
        totalStudents: 980,
        internationalStudents: 200,
        studentTeacherRatio: '5:1',
        avgClassSize: 13,
        graduationRate: 100,
        collegeAcceptanceRate: 98,
        satAverage: 1455,
        apCourses: 32,
      },
      programs: ['STEM', 'Arts Integration', 'Community Engagement', 'Global Programs', 'Entrepreneurship', 'Language Immersion'],
      sports: ['Ice Hockey', 'Sailing', 'Skiing', 'Track & Field', 'Soccer', 'Rowing', 'Tennis'],
      arts: ['Straus Center for the Arts', 'Theater', 'Music', 'Dance', 'Visual Arts'],
      facilities: ['Straus Arts Center', 'Forbes House Museum Access', 'Athletics Complex', 'Science Wing', 'Innovation Studio', 'Boston City Access'],
      contactInfo: {
        email: 'admission@milton.edu',
        phone: '+1 (617) 898-1798',
        website: 'https://www.milton.edu',
        admissionsEmail: 'admission@milton.edu',
      },
      accreditation: ['NEASC'],
      affiliations: ['Eight Schools Association'],
      featured: true,
    },
  ]);

  const scholarships = [
    // ─── Phillips Exeter ───────────────────────────────────
    {
      school: schools[0]._id,
      name: 'Exeter Global Excellence Full Scholarship',
      slug: slug('Exeter Global Excellence Full Scholarship'),
      isActive: true,
      type: 'full',
      coveragePercentage: 100,
      annualValue: 750000,
      totalValue: 3000000,
      duration: { years: 4, renewable: true, renewalCriteria: 'Maintain 3.7+ GPA and active community involvement' },
      benefits: {
        fullTuition: true,
        boarding: true,
        meals: true,
        books: true,
        healthInsurance: true,
        airfare: true,
        satPrep: true,
        mentorship: true,
        internship: true,
        collegeGuidance: true,
        leadershipPrograms: true,
        stemMentorship: true,
        academicCounseling: true,
        custom: ['Annual Stipend $5,000', 'Laptop & Tech Package', 'Study Abroad Access', 'Alumni Network Lifetime Access', 'Summer Research Fellowship'],
      },
      remainingTuition: 0,
      enrollmentDeposit: 500,
      eligibility: {
        grades: ['9', '10'],
        minGpa: 3.8,
        nationalities: [],
        ageMin: 13,
        ageMax: 16,
        englishProficiency: 'TOEFL 95+ or IELTS 7.0+',
      },
      applicationDeadline: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
      description: 'The pinnacle of international scholarships at Phillips Exeter Academy — our most prestigious and comprehensive fully-funded program. Covering 100% of all costs with a total package value of $3,000,000 over four years, this scholarship is awarded to exceptional international students who demonstrate extraordinary academic achievement, leadership potential, and global citizenship. Recipients join a community of scholars who go on to change the world.',
      highlights: [
        'Total value: $3,000,000 over 4 years',
        'Zero remaining costs — completely free',
        'Annual $5,000 personal stipend',
        'Airfare covered both ways every year',
        'Direct mentorship from Exeter alumni at top universities',
        'Guaranteed internship placement in Year 3',
        'College counseling for Ivy League admission',
        'Lifetime alumni network access',
      ],
      selectionCriteria: ['Academic excellence (Top 2% nationally)', 'Leadership & community impact', 'Creative problem solving', 'Interview performance', 'Teacher recommendations'],
      applicationRequirements: ['Official academic transcripts (past 3 years)', 'Certified English translation of transcripts', 'Valid passport copy', 'TOEFL/IELTS score report', 'Two teacher recommendation letters', 'Principal/Headmaster recommendation', 'Personal statement (800–1000 words)', 'Essay: "How will you contribute to Exeter?" (500 words)', 'Recent passport-style photo'],
      slotsTotal: 10,
      featured: true,
    },
    {
      school: schools[0]._id,
      name: 'Exeter International STEM Leadership Scholarship',
      slug: slug('Exeter International STEM Leadership Scholarship'),
      isActive: true,
      type: 'stem',
      coveragePercentage: 85,
      annualValue: 382500,
      totalValue: 1530000,
      duration: { years: 4, renewable: true, renewalCriteria: 'Maintain 3.6+ GPA and participate in STEM activities' },
      benefits: {
        tuition: true,
        boarding: true,
        meals: true,
        books: true,
        healthInsurance: true,
        satPrep: true,
        stemMentorship: true,
        mentorship: true,
        internship: true,
        collegeGuidance: true,
        academicCounseling: true,
        custom: ['STEM Research Lab Access', 'Annual $3,000 Research Grant', 'Silicon Valley Tour', 'MIT/Caltech Visit Program'],
      },
      remainingTuition: 112500,
      enrollmentDeposit: 500,
      eligibility: {
        grades: ['9', '10', '11'],
        minGpa: 3.7,
        nationalities: [],
        ageMin: 13,
        ageMax: 17,
        englishProficiency: 'TOEFL 90+ or IELTS 6.5+',
      },
      applicationDeadline: new Date(Date.now() + 75 * 24 * 60 * 60 * 1000),
      description: 'Designed for the next generation of scientists, engineers, and innovators, the Exeter STEM Leadership Scholarship provides 85% tuition coverage with exceptional STEM-focused benefits. With a total value of $1,530,000, this scholarship gives exceptional international students access to Exeter\'s world-class science facilities and industry mentors from Silicon Valley and leading research institutions.',
      highlights: [
        'Total value: $1,530,000 over 4 years',
        '85% tuition coverage',
        'Annual $3,000 STEM research grant',
        'Access to Exeter\'s cutting-edge science labs',
        'Silicon Valley immersion tour',
        'Mentorship from MIT, Caltech & Stanford alumni',
        'Guaranteed research internship in Year 3',
      ],
      selectionCriteria: ['Outstanding Math/Science grades', 'STEM competition achievements', 'Innovation mindset', 'English proficiency', 'Teacher recommendations in STEM subjects'],
      applicationRequirements: ['Academic transcripts', 'Passport copy', 'TOEFL/IELTS score report', 'Two teacher recommendations (Math & Science)', 'Personal statement', 'STEM project portfolio or competition results', 'Photo'],
      slotsTotal: 20,
      featured: true,
    },

    // ─── Andover ──────────────────────────────────────────
    {
      school: schools[1]._id,
      name: 'Andover Presidential Merit Scholarship',
      slug: slug('Andover Presidential Merit Scholarship'),
      isActive: true,
      type: 'full',
      coveragePercentage: 100,
      annualValue: 810000,
      totalValue: 3000000,
      duration: { years: 4, renewable: true, renewalCriteria: 'Maintain 3.7+ GPA and embody Andover\'s values' },
      benefits: {
        fullTuition: true,
        boarding: true,
        meals: true,
        books: true,
        uniform: true,
        healthInsurance: true,
        airfare: true,
        satPrep: true,
        mentorship: true,
        internship: true,
        collegeGuidance: true,
        leadershipPrograms: true,
        academicCounseling: true,
        custom: ['Annual Stipend $6,000', 'Complete Tech Package (MacBook + iPad)', 'Andover Alumni Network', 'Washington D.C. Policy Immersion', 'Harvard / MIT Campus Visits', 'Summer Abroad Program'],
      },
      remainingTuition: 0,
      enrollmentDeposit: 500,
      eligibility: {
        grades: ['9', '10'],
        minGpa: 3.8,
        nationalities: [],
        ageMin: 13,
        ageMax: 16,
        englishProficiency: 'TOEFL 100+ or IELTS 7.0+',
      },
      applicationDeadline: new Date(Date.now() + 85 * 24 * 60 * 60 * 1000),
      description: 'The Andover Presidential Merit Scholarship is awarded to one extraordinary international student per cohort who demonstrates the potential to shape the future of humanity. With a total value of $3,000,000 — covering absolutely everything including a $6,000 annual stipend — this is the most transformative opportunity in international high school education. Join a lineage of world leaders, Nobel laureates, and change-makers who called Andover home.',
      highlights: [
        'Total value: $3,000,000 over 4 years',
        '100% fully funded — zero out-of-pocket costs',
        'Annual $6,000 personal stipend',
        'Complete tech package included',
        'Policy immersion trip to Washington D.C.',
        'Harvard & MIT campus visits',
        'Fully funded summer abroad program',
        'Direct mentorship from Andover presidential alumni',
      ],
      selectionCriteria: ['Academic transcripts showing exceptional performance', 'National or international award/recognition', 'Leadership in school or community', 'Compelling personal narrative', 'Video essay submission', 'Panel interview'],
      applicationRequirements: ['Official transcripts (3 years)', 'Certified English translation', 'Passport copy', 'TOEFL/IELTS report', 'Three recommendation letters', 'Personal statement (1000 words)', 'Video essay (3 minutes)', 'List of awards and achievements', 'Passport photo'],
      slotsTotal: 8,
      featured: true,
    },
    {
      school: schools[1]._id,
      name: 'Andover International Arts Excellence Award',
      slug: slug('Andover International Arts Excellence Award'),
      isActive: true,
      type: 'arts',
      coveragePercentage: 80,
      annualValue: 324000,
      totalValue: 1296000,
      duration: { years: 4, renewable: true, renewalCriteria: 'Maintain 3.4+ GPA and active participation in arts programs' },
      benefits: {
        tuition: true,
        boarding: true,
        meals: true,
        books: true,
        healthInsurance: true,
        mentorship: true,
        collegeGuidance: true,
        academicCounseling: true,
        custom: ['Addison Gallery VIP Access', 'Annual Arts Materials Budget $2,500', 'NYC Arts Immersion Trip', 'Professional Portfolio Development', 'MFA Exhibition Opportunity'],
      },
      remainingTuition: 81000,
      enrollmentDeposit: 500,
      eligibility: {
        grades: ['9', '10', '11'],
        minGpa: 3.4,
        nationalities: [],
        ageMin: 13,
        ageMax: 17,
        englishProficiency: 'TOEFL 85+ or IELTS 6.5+',
      },
      applicationDeadline: new Date(Date.now() + 70 * 24 * 60 * 60 * 1000),
      description: 'The Andover International Arts Excellence Award celebrates students who combine academic brilliance with exceptional creative talent. With a total package value of $1,296,000 and 80% coverage, this scholarship provides access to Andover\'s world-renowned Addison Gallery of American Art and professional-level arts training. Recipients go on to attend the world\'s top art schools and conservatories.',
      highlights: [
        'Total value: $1,296,000 over 4 years',
        '80% coverage + full boarding',
        'Annual $2,500 arts materials budget',
        'VIP access to the Addison Gallery',
        'NYC arts and gallery immersion trip',
        'Professional portfolio development support',
        'Exhibition opportunities',
      ],
      selectionCriteria: ['Academic transcripts', 'Portfolio submission (10–15 works)', 'Artistic statement', 'Teacher recommendation (Art teacher required)', 'Interview or audition'],
      applicationRequirements: ['Academic transcripts', 'Passport copy', 'TOEFL/IELTS report', 'Art portfolio (digital submission)', 'Artist statement (500 words)', 'Two recommendation letters (one must be from arts teacher)', 'Photo'],
      slotsTotal: 18,
      featured: false,
    },

    // ─── Lawrenceville ────────────────────────────────────
    {
      school: schools[2]._id,
      name: 'Lawrenceville Global Scholars Full Scholarship',
      slug: slug('Lawrenceville Global Scholars Full Scholarship'),
      isActive: true,
      type: 'full',
      coveragePercentage: 100,
      annualValue: 750000,
      totalValue: 3000000,
      duration: { years: 4, renewable: true, renewalCriteria: 'Maintain 3.6+ GPA and contribute to the house community' },
      benefits: {
        fullTuition: true,
        boarding: true,
        meals: true,
        books: true,
        uniform: true,
        healthInsurance: true,
        airfare: true,
        satPrep: true,
        mentorship: true,
        internship: true,
        collegeGuidance: true,
        leadershipPrograms: true,
        stemMentorship: true,
        academicCounseling: true,
        custom: ['Annual Stipend $4,500', 'Princeton University Campus Access', 'Global Leadership Summit Invitation', 'Annual International Travel Grant $3,000', 'Harkness Leadership Program'],
      },
      remainingTuition: 0,
      enrollmentDeposit: 500,
      eligibility: {
        grades: ['9', '10'],
        minGpa: 3.7,
        nationalities: [],
        ageMin: 13,
        ageMax: 16,
        englishProficiency: 'TOEFL 95+ or IELTS 7.0+',
      },
      applicationDeadline: new Date(Date.now() + 80 * 24 * 60 * 60 * 1000),
      description: 'The Lawrenceville Global Scholars Scholarship is the ultimate expression of Lawrenceville\'s belief in transformative international education. With a total value of $3,000,000, this fully-funded scholarship covers every conceivable expense, including annual stipend and international travel grants. Located minutes from Princeton University, scholars gain unparalleled access to elite academic and research environments.',
      highlights: [
        'Total value: $3,000,000 over 4 years',
        '100% fully funded — all costs covered',
        'Annual $4,500 personal stipend',
        'Princeton University campus access & events',
        'Annual $3,000 international travel grant',
        'Global Leadership Summit invitation',
        'Harkness leadership training',
        'Full college counseling for Princeton, Yale, Harvard',
      ],
      selectionCriteria: ['Exceptional academic record', 'Community leadership', 'Character and resilience', 'Interview performance', 'Written essays'],
      applicationRequirements: ['Official transcripts (3 years)', 'Certified English translation', 'Passport copy', 'TOEFL/IELTS report', 'Three letters of recommendation', 'Personal statement', 'Leadership essay (500 words)', 'Photo'],
      slotsTotal: 12,
      featured: true,
    },
    {
      school: schools[2]._id,
      name: 'Lawrenceville STEM Innovation Scholarship',
      slug: slug('Lawrenceville STEM Innovation Scholarship'),
      isActive: true,
      type: 'stem',
      coveragePercentage: 75,
      annualValue: 262500,
      totalValue: 1050000,
      duration: { years: 4, renewable: true, renewalCriteria: 'Maintain 3.5+ GPA and participate in STEM Innovation Lab' },
      benefits: {
        tuition: true,
        boarding: true,
        meals: true,
        healthInsurance: true,
        satPrep: true,
        stemMentorship: true,
        mentorship: true,
        internship: true,
        collegeGuidance: true,
        academicCounseling: true,
        custom: ['Princeton STEM Lab Access', 'Annual Research Grant $2,000', 'Innovation Lab Priority Access', 'Startup Mentorship Program', 'National Science Competition Sponsorship'],
      },
      remainingTuition: 87500,
      enrollmentDeposit: 500,
      eligibility: {
        grades: ['9', '10', '11'],
        minGpa: 3.6,
        nationalities: [],
        ageMin: 13,
        ageMax: 17,
        englishProficiency: 'TOEFL 88+ or IELTS 6.5+',
      },
      applicationDeadline: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000),
      description: 'The Lawrenceville STEM Innovation Scholarship is purpose-built for students who want to push the boundaries of science and technology. With a total value of $1,050,000 and 75% coverage, this scholarship opens doors to Lawrenceville\'s Innovation Lab and direct access to Princeton University\'s STEM resources. Scholars are mentored by leading scientists and entrepreneurs.',
      highlights: [
        'Total value: $1,050,000 over 4 years',
        '75% tuition coverage + full boarding & meals',
        'Princeton University STEM lab access',
        'Annual $2,000 research grant',
        'Innovation Lab priority access',
        'Startup mentorship program',
        'National science competition sponsorship',
      ],
      selectionCriteria: ['Top grades in Math & Science', 'STEM competition results', 'Research or innovation project', 'STEM teacher recommendation', 'Interview'],
      applicationRequirements: ['Academic transcripts', 'Passport copy', 'TOEFL/IELTS report', 'Two recommendation letters (Math/Science teachers)', 'Personal statement', 'STEM project description or portfolio', 'Photo'],
      slotsTotal: 22,
      featured: true,
    },

    // ─── Hotchkiss ────────────────────────────────────────
    {
      school: schools[3]._id,
      name: 'Hotchkiss World Scholars Full Scholarship',
      slug: slug('Hotchkiss World Scholars Full Scholarship'),
      isActive: true,
      type: 'full',
      coveragePercentage: 100,
      annualValue: 877500,
      totalValue: 3000000,
      duration: { years: 4, renewable: true, renewalCriteria: 'Maintain 3.6+ GPA and demonstrate ongoing community leadership' },
      benefits: {
        fullTuition: true,
        boarding: true,
        meals: true,
        books: true,
        uniform: true,
        healthInsurance: true,
        airfare: true,
        satPrep: true,
        mentorship: true,
        internship: true,
        collegeGuidance: true,
        leadershipPrograms: true,
        academicCounseling: true,
        custom: ['Annual Stipend $5,500', 'Ludd Museum Access & Curatorship', 'Annual Ski Pass', 'Language Immersion Abroad Program', 'Global Policy Forum Invitation', 'Tech Package (Laptop + Tablet)'],
      },
      remainingTuition: 0,
      enrollmentDeposit: 500,
      eligibility: {
        grades: ['9', '10'],
        minGpa: 3.75,
        nationalities: [],
        ageMin: 14,
        ageMax: 16,
        englishProficiency: 'TOEFL 95+ or IELTS 7.0+',
      },
      applicationDeadline: new Date(Date.now() + 95 * 24 * 60 * 60 * 1000),
      description: 'The Hotchkiss World Scholars Scholarship is the crown jewel of international educational funding — a $3,000,000 four-year package that leaves absolutely nothing to chance. Set on a magnificent 545-acre campus in Connecticut\'s scenic Berkshire foothills, Hotchkiss offers a truly extraordinary environment for the world\'s most gifted young minds. This scholarship covers everything including a generous annual stipend and a fully-funded language immersion abroad program.',
      highlights: [
        'Total value: $3,000,000 over 4 years',
        '100% fully funded — every expense covered',
        'Annual $5,500 personal stipend',
        'Fully funded language immersion abroad program',
        'Hotchkiss Art Museum curatorial access',
        'Ski pass included (campus ski hill)',
        'Global Policy Forum annual invitation',
        'Complete tech package',
      ],
      selectionCriteria: ['Exceptional academic achievement', 'Demonstrated leadership', 'Global perspective', 'Creative and critical thinking', 'Two-round interview process'],
      applicationRequirements: ['Official transcripts', 'Certified translations', 'Passport copy', 'TOEFL/IELTS report', 'Three recommendation letters', 'Personal statement (800 words)', 'Global leadership essay (400 words)', 'Photo'],
      slotsTotal: 8,
      featured: true,
    },
    {
      school: schools[3]._id,
      name: 'Hotchkiss International Merit Award',
      slug: slug('Hotchkiss International Merit Award'),
      isActive: true,
      type: 'merit',
      coveragePercentage: 65,
      annualValue: 282750,
      totalValue: 1131000,
      duration: { years: 4, renewable: true, renewalCriteria: 'Maintain 3.4+ GPA' },
      benefits: {
        tuition: true,
        boarding: true,
        meals: true,
        books: true,
        healthInsurance: true,
        satPrep: true,
        mentorship: true,
        collegeGuidance: true,
        academicCounseling: true,
        custom: ['Campus Ski Pass', 'Annual $1,500 Activity Budget', 'College Prep Program', 'Alumni Mentorship Pairing'],
      },
      remainingTuition: 152250,
      enrollmentDeposit: 500,
      eligibility: {
        grades: ['9', '10', '11'],
        minGpa: 3.5,
        nationalities: [],
        ageMin: 13,
        ageMax: 17,
        englishProficiency: 'TOEFL 85+ or IELTS 6.5+',
      },
      applicationDeadline: new Date(Date.now() + 65 * 24 * 60 * 60 * 1000),
      description: 'The Hotchkiss International Merit Award recognizes outstanding international students with strong academic records and a demonstrated commitment to their communities. With a total value exceeding $1,131,000 and 65% coverage including full boarding and meals, this scholarship opens the doors of one of America\'s most beautiful and academically distinguished boarding schools.',
      highlights: [
        'Total value: $1,131,000 over 4 years',
        '65% tuition coverage + full boarding',
        'Ski pass to campus ski hill',
        'Annual $1,500 activity budget',
        'Personalized college prep program',
        'Alumni mentorship pairing',
      ],
      selectionCriteria: ['Strong academic record', 'Community involvement', 'Character and integrity', 'Teacher recommendations', 'Interview'],
      applicationRequirements: ['Academic transcripts', 'Passport copy', 'TOEFL/IELTS report', 'Two recommendation letters', 'Personal statement', 'Photo'],
      slotsTotal: 25,
      featured: false,
    },

    // ─── Deerfield ────────────────────────────────────────
    {
      school: schools[4]._id,
      name: 'Deerfield Academy Pioneer Full Scholarship',
      slug: slug('Deerfield Academy Pioneer Full Scholarship'),
      isActive: true,
      type: 'full',
      coveragePercentage: 100,
      annualValue: 750000,
      totalValue: 3000000,
      duration: { years: 4, renewable: true, renewalCriteria: 'Maintain 3.6+ GPA, community service hours, and dorm leadership' },
      benefits: {
        fullTuition: true,
        boarding: true,
        meals: true,
        books: true,
        uniform: true,
        healthInsurance: true,
        airfare: true,
        satPrep: true,
        mentorship: true,
        internship: true,
        collegeGuidance: true,
        leadershipPrograms: true,
        stemMentorship: true,
        academicCounseling: true,
        custom: ['Annual Stipend $5,000', 'Historic Deerfield Cultural Access', 'Boston Museum & Gallery Passes', 'Annual Research Grant $2,500', 'Ivy League Campus Tour Package'],
      },
      remainingTuition: 0,
      enrollmentDeposit: 500,
      eligibility: {
        grades: ['9', '10'],
        minGpa: 3.75,
        nationalities: [],
        ageMin: 13,
        ageMax: 16,
        englishProficiency: 'TOEFL 95+ or IELTS 7.0+',
      },
      applicationDeadline: new Date(Date.now() + 88 * 24 * 60 * 60 * 1000),
      description: 'Named after the pioneering spirit of one of America\'s oldest academies, the Deerfield Pioneer Full Scholarship is a $3,000,000 testament to the belief that exceptional students deserve an exceptional education — regardless of where they were born. This fully-funded scholarship provides complete financial security so scholars can focus entirely on learning, growing, and becoming tomorrow\'s leaders.',
      highlights: [
        'Total value: $3,000,000 over 4 years',
        '100% fully funded — zero out-of-pocket',
        'Annual $5,000 personal stipend',
        'Annual $2,500 research/project grant',
        'Historic Deerfield cultural immersion access',
        'Boston museum & gallery annual passes',
        'Full Ivy League campus tour package',
        'Comprehensive Ivy League college counseling',
      ],
      selectionCriteria: ['Outstanding academic performance', 'Demonstrated leadership', 'Community service record', 'Intellectual curiosity', 'Two-stage interview'],
      applicationRequirements: ['Official transcripts (3 years)', 'Certified English translation', 'Passport copy', 'TOEFL/IELTS report', 'Three recommendation letters', 'Personal essay (900 words)', 'Leadership impact essay (400 words)', 'Photo'],
      slotsTotal: 10,
      featured: true,
    },
    {
      school: schools[4]._id,
      name: 'Deerfield Need-Based Access Scholarship',
      slug: slug('Deerfield Need-Based Access Scholarship'),
      isActive: true,
      type: 'need-based',
      coveragePercentage: 70,
      annualValue: 294000,
      totalValue: 1176000,
      duration: { years: 4, renewable: true, renewalCriteria: 'Maintain 3.3+ GPA and continue to demonstrate financial need' },
      benefits: {
        tuition: true,
        boarding: true,
        meals: true,
        books: true,
        healthInsurance: true,
        satPrep: true,
        mentorship: true,
        collegeGuidance: true,
        academicCounseling: true,
        custom: ['Annual $2,000 Family Support Grant', 'Travel Assistance Program', 'Textbook & Supply Program', 'Peer Support Mentorship'],
      },
      remainingTuition: 126000,
      enrollmentDeposit: 500,
      eligibility: {
        grades: ['9', '10', '11'],
        minGpa: 3.4,
        nationalities: [],
        ageMin: 13,
        ageMax: 17,
        englishProficiency: 'TOEFL 85+ or IELTS 6.5+',
        other: ['Must demonstrate financial need', 'Family income documentation required'],
      },
      applicationDeadline: new Date(Date.now() + 72 * 24 * 60 * 60 * 1000),
      description: 'The Deerfield Need-Based Access Scholarship removes financial barriers for talented students whose families cannot afford the full cost of a Deerfield education. With a total value of $1,176,000 and 70% coverage, this scholarship ensures that economic circumstances never determine a student\'s educational destiny. Additional family support grants and travel assistance make this truly accessible.',
      highlights: [
        'Total value: $1,176,000 over 4 years',
        '70% tuition + full boarding & meals',
        'Annual $2,000 family support grant',
        'Travel assistance program',
        'Textbook and supplies fully covered',
        'Dedicated peer support mentorship',
      ],
      selectionCriteria: ['Academic merit', 'Demonstrated financial need', 'Character and resilience', 'Community contribution', 'Recommendation letters'],
      applicationRequirements: ['Academic transcripts', 'Passport copy', 'TOEFL/IELTS report', 'Financial need documentation', 'Two recommendation letters', 'Personal statement', 'Essay: "How has financial challenge shaped you?" (400 words)', 'Photo'],
      slotsTotal: 30,
      featured: false,
    },

    // ─── Milton ───────────────────────────────────────────
    {
      school: schools[5]._id,
      name: 'Milton Academy Global Leaders Full Scholarship',
      slug: slug('Milton Academy Global Leaders Full Scholarship'),
      isActive: true,
      type: 'full',
      coveragePercentage: 100,
      annualValue: 750000,
      totalValue: 3000000,
      duration: { years: 4, renewable: true, renewalCriteria: 'Maintain 3.6+ GPA and contribute to community initiatives' },
      benefits: {
        fullTuition: true,
        boarding: true,
        meals: true,
        books: true,
        uniform: true,
        healthInsurance: true,
        airfare: true,
        satPrep: true,
        mentorship: true,
        internship: true,
        collegeGuidance: true,
        leadershipPrograms: true,
        stemMentorship: true,
        academicCounseling: true,
        custom: ['Annual Stipend $5,000', 'Boston City Cultural Pass', 'Harvard & MIT Regular Visits', 'Annual Social Impact Project Grant $3,000', 'Public Policy Internship', 'Complete Tech Package'],
      },
      remainingTuition: 0,
      enrollmentDeposit: 500,
      eligibility: {
        grades: ['9', '10'],
        minGpa: 3.75,
        nationalities: [],
        ageMin: 13,
        ageMax: 16,
        englishProficiency: 'TOEFL 95+ or IELTS 7.0+',
      },
      applicationDeadline: new Date(Date.now() + 92 * 24 * 60 * 60 * 1000),
      description: 'The Milton Academy Global Leaders Scholarship harnesses the unique advantage of being 8 miles from Boston — one of the world\'s greatest academic cities — to create an unparalleled $3,000,000 fully-funded educational experience. Scholars enjoy regular visits to Harvard and MIT, a $3,000 annual social impact grant, and a public policy internship in Boston\'s vibrant civic sector. This is where global leaders are made.',
      highlights: [
        'Total value: $3,000,000 over 4 years',
        '100% fully funded — zero cost to family',
        'Annual $5,000 personal stipend',
        'Regular Harvard & MIT campus visits and events',
        'Annual $3,000 social impact project grant',
        'Boston city cultural pass',
        'Public policy internship in Boston',
        'Complete tech package included',
      ],
      selectionCriteria: ['Exceptional academic achievement', 'Social impact and leadership', 'Boston connection or global urban interest', 'Creative thinking', 'Two-stage interview'],
      applicationRequirements: ['Official transcripts (3 years)', 'Certified English translation', 'Passport copy', 'TOEFL/IELTS report', 'Three recommendation letters', 'Personal statement (800 words)', 'Social impact essay (500 words)', 'Photo'],
      slotsTotal: 10,
      featured: true,
    },
    {
      school: schools[5]._id,
      name: 'Milton International Partial Scholarship',
      slug: slug('Milton International Partial Scholarship'),
      isActive: true,
      type: 'partial',
      coveragePercentage: 60,
      annualValue: 240000,
      totalValue: 1000000,
      duration: { years: 4, renewable: true, renewalCriteria: 'Maintain 3.3+ GPA' },
      benefits: {
        tuition: true,
        boarding: true,
        meals: true,
        healthInsurance: true,
        satPrep: true,
        mentorship: true,
        collegeGuidance: true,
        academicCounseling: true,
        custom: ['Boston Cultural Pass', 'Annual $1,500 Activity Allowance', 'Peer Mentorship Program', 'College Application Workshop Series'],
      },
      remainingTuition: 160000,
      enrollmentDeposit: 500,
      eligibility: {
        grades: ['9', '10', '11'],
        minGpa: 3.3,
        nationalities: [],
        ageMin: 13,
        ageMax: 17,
        englishProficiency: 'TOEFL 80+ or IELTS 6.0+',
      },
      applicationDeadline: new Date(Date.now() + 55 * 24 * 60 * 60 * 1000),
      description: 'The Milton International Partial Scholarship makes a Milton Academy education accessible to a broader group of talented international students. With a total value of $1,000,000 and 60% coverage plus full boarding and meals, this scholarship provides a solid financial foundation for students ready to thrive in Milton\'s dynamic, Boston-adjacent campus environment.',
      highlights: [
        'Total value: $1,000,000 over 4 years',
        '60% tuition + full boarding & meals',
        'Boston cultural city pass',
        'Annual $1,500 activity allowance',
        'College application workshop series',
        'Access to Harvard & MIT campus events',
      ],
      selectionCriteria: ['Good academic record', 'Positive attitude and community spirit', 'English proficiency', 'Teacher recommendations', 'Interview'],
      applicationRequirements: ['Academic transcripts', 'Passport copy', 'TOEFL/IELTS report', 'Two recommendation letters', 'Personal statement (600 words)', 'Photo'],
      slotsTotal: 35,
      featured: false,
    },
  ];

  await Scholarship.insertMany(scholarships);
  console.log(`✅ Seeded ${schools.length} schools and ${scholarships.length} scholarships`);
  console.log('\n💰 Scholarship Value Summary:');
  console.log('  Full scholarships: $3,000,000 total (4 years)');
  console.log('  STEM scholarships: $1,050,000 – $1,530,000 total');
  console.log('  Partial scholarships: $1,000,000 – $1,296,000 total');
  console.log('  All scholarships start at minimum $1,000,000 total value');
  process.exit(0);
};

seed().catch(err => { console.error(err); process.exit(1); });